### ISSUE TITLE
Copied AreaProtect

### ISSUE THREAD

**Issue by Gamecrafter** [ZenaGamingsky/LandProtect-Master#3]
It appears that you copied @ComedyMan937's AreaProtect. This is called plagiarism. https://github.com/comedyman937/areaprotect You are pathetic if you think you could fool anyone of us. I bet it took you two/three days to COPY the code. XD

**Comment by KyleTheHack3r** [comment]
Agreed. You can't even create a directory using GitHub.

**Comment by Gamecrafter** [comment]
Obviously a noob. Didn't even bother to change the order of code and any of the variables! What a fail...

**Comment by Comedyman937** [comment]
I hope you realize you can be banned from the PocketMine forums for copying code...

**Comment by ZenaGamingsky** [comment]
I don't publish plugin that was just a test plugin

**Comment by Gamecrafter** [comment]
Excuses excuses. If it was a test plugin it should have been your own code, not DA_Swagnemite aka Comedyman937's code.

**Comment by ZenaGamingsky** [comment]
I am leaning simple login code I am making that plugin

**Comment by Gamecrafter** [comment]
That isn't learning when you copy other peoples' code, learn here: docs.pocketmine.net or here: codecademy.com

**Comment by ZenaGamingsky** [comment]
Fuck off

**Comment by Gamecrafter** [comment]
^ Rage, haha.

**Comment by ZenaGamingsky** [comment]
hahah your skick

**Comment by Gamecrafter** [comment]
Your skick?

**Comment by KyleTheHack3r** [comment]
Haha, he's mad.

**Comment by Gamecrafter** [comment]
Haha, he's enraged.
